### PR TITLE
kinematics calculator added

### PR DESCRIPTION
**Pull request by Shoray2002**
## Related Issue

- Add Kinematics Calculator in Classical Mechanics section

Fixes: #54 

#### Describe the changes you've made
Added calculation support for the three fundamental equation of motion.
Added a dropdown menu to let the user select the quantity they want to find and also made the page responsive

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

## Screenshots

<a href="https://ibb.co/k5d0htX">Fun-With-Physics-Mozilla-Firefox-05-10-2021-16-50-37</a> <a href="https://ibb.co/B6xtTfX">Fun-With-Physics-Mozilla-Firefox-05-10-2021-16-51-16</a>
<a href="https://ibb.co/rHFVcKt">Fun-With-Physics-Mozilla-Firefox-05-10-2021-16-53-16</a>

### CODE REVIEW

**Comment by Amit366** [comment]
@Shoray2002 resolve the conflicts

**Comment by Shoray2002** [comment]
conflicts resolved

**Comment by Amit366** [comment]
@Shoray2002 resolve the error as soon as possible. check discord

**Comment by Shoray2002** [comment]
> @Shoray2002 resolve the error as soon as possible. check discord

What error?

**Pull request merged**
