### PR TITLE
More Physics Formulas

### PR DESCRIPTION
**Pull request by ShivamDecodes**
## Related Issue

- Added more formulas for ease

Fixes: #[it was not an issue, its a complementary work]

#### added more formulas and SI units of different physical measurements.

Made A New Folder And Added The Formulas In It. It will be great if users also get the formula sheet(obviously at a seperate point!). That would create ease in using it.

### CODE REVIEW

**Comment by Amit366** [comment]
@ShivamDecodes first of all its a calculator project so there is no point of formula sheet. Even if you have created it how can users view it as there is no button or anything. It's not only a GitHub repo it is also live. So if u find solutions to these then comment it.

**Comment by ShivamDecodes** [comment]
Ok Sorry For wasting Your time bhaiya!
Now, 
Can I Make A Soft UI Graphics For Your Calculator Or Splash Screen Animation For It?
I can Also Do What You Assign me to.

**Comment by Amit366** [comment]
@ShivamDecodes what do u mean by soft UI like can u give any example?

**Comment by ShivamDecodes** [comment]
Yes!
Soft UI is a type of theme that looks like:-

**Comment by Amit366** [comment]
@ShivamDecodes but I think this will be good is there are many buttons. But in the calculator page there are no buttons. So will it look nice??

**Comment by ShivamDecodes** [comment]
Well,
We Can Try!
Don't Worry About It 
I Will Be Trying New Things Here...😊

**Comment by ShivamDecodes** [comment]
Can You Please Send The Output Screenshot Of Our Project?

**Comment by Amit366** [comment]
@ShivamDecodes the link is in the readme file

**Comment by Amit366** [comment]
@ShivamDecodes r u working on any issue??

**Comment by ShivamDecodes** [comment]
> @ShivamDecodes r u working on any issue??

Yes I am trying to make the full applet on firebase and Django for algo but...
It's not getting right way...
It will take much time😔

**Comment by Amit366** [comment]
@ShivamDecodes u r making an app?

**Comment by ShivamDecodes** [comment]
> @ShivamDecodes u r making an app? 

Yes something like that...

**Comment by ShivamDecodes** [comment]
> @ShivamDecodes u r making an app? 

Yes something like that...

**Comment by Amit366** [comment]
@ShivamDecodes then do one thing close this PR, and open an issue on what you r doing. And also join the discord channel link in readme for discussion

**Comment by ShivamDecodes** [comment]
> @ShivamDecodes then do one thing close this PR, and open an issue on what you r doing. And also join the discord channel link in readme for discussion

Can I do it tomorrow..?
I Have an ongoing test from 8 pm?

**Comment by Amit366** [comment]
@ShivamDecodes u r free to do in ur free time. But ifu  r working on any thing then just open up an issue so that I can assign u or else if anyone gets this idea then I have to assign that person this issue as u haven't created any such issue.

**Comment by ShivamDecodes** [comment]
> @ShivamDecodes u r free to do in ur free time. But ifu  r working on any thing then just open up an issue so that I can assign u or else if anyone gets this idea then I have to assign that person this issue as u haven't created any such issue. 

No Bro!
The Project I Was Trying too make is full of bugs and this will make our project more complex.
I Was Trying to have an AI calculator but to use it you may need specific hardware which is not in everyone's hand.
So, I have dropped this idea. Hope You may understand.🙂

**Pull request closed without merging**
