### PR TITLE
Homepage added

### PR DESCRIPTION
**Pull request by aakankshabhende**

### CODE REVIEW

**Comment by Amit366** [comment]
@aakankshabhende can u send a screenshot of the home page?

**Comment by aakankshabhende** [comment]
Screenshot (234)
Screenshot (235)
Screenshot (236)

**Comment by Amit366** [comment]
Its look good.

**Comment by Amit366** [comment]
But one thing could you make the heading a little different ?  Like leave some space for the logo

**Comment by aakankshabhende** [comment]
I assumed that instead of Fun with physics in navbar there will be logo in future @Amit366

**Comment by Amit366** [comment]
No there will be both the logo and navbar. If you can then do it else not required. @aakankshabhende

**Comment by aakankshabhende** [comment]
Okay I'll do

**Comment by aakankshabhende** [comment]
How to link PR with issue? @Amit366

**Comment by Amit366** [comment]
Just write Fixes: #issue number

**Comment by aakankshabhende** [comment]
Instead of those icons logo will be there 
Screenshot (237)

**Comment by Amit366** [comment]
Ok cool .  Just link the PR with the issue in the format mentioned

**Comment by aakankshabhende** [comment]
Fixes: #1

**Comment by Amit366** [comment]
@all-contributors please add @aakankshabhende

**Comment by Amit366** [comment]
@all-contributors please add @aakankshabhende for feature

**Comment by Amit366** [comment]
@all-contributors please add @aakankshabhende for design

**Pull request merged**
