### PR TITLE
modification: FAQ page

### PR DESCRIPTION
**Pull request by souravseal99**
## Modification of FAQ page, issue: #49 

- adding a proper popup to the FAQ page.

Fixes: #49 

#### Describe the changes you've made
- Added a modal to the FAQ link in the Navbar
- Fixed the .gitignore, which was causing the node_modules to be in staging area.

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
#### Added Files & Packages
.gitignore 
react-bootstrap 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **image** | <b>image </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@souravseal99 it's nice but just reduce the font of the question a little as the answer are of small font.

**Comment by souravseal99** [comment]
> @souravseal99 it's nice but just reduce the font of the question a little as the answer are of small font. 

Sure @Amit366

**Comment by souravseal99** [comment]
> @souravseal99 it's nice but just reduce the font of the question a little as the answer are of small font.

Should I make a change Like this ?

image

**Comment by Amit366** [comment]
@souravseal99 it's fine. Just make the 'w' in 'what' upper case

**Comment by souravseal99** [comment]
> @souravseal99 it's fine. Just make the 'w' in 'what' upper case

ok, sure...

**Comment by Amit366** [comment]
@souravseal99 if u want try out the calculators also

**Comment by souravseal99** [comment]
> @souravseal99 if u want try out the calculators also

yes sure @Amit366 , I'm looking into it.

**Comment by Amit366** [comment]
@souravseal99 also fill the form

**Comment by souravseal99** [comment]
Thanks @Amit366 .

**Pull request merged**
