### PR TITLE
Bug/gravitation page

### PR DESCRIPTION
**Pull request by laisfrigerio**
## Related Issue

- Info about Issue or bug

Fixes: #73 

## Checklist:

- [x] Add gravitation data into wpe_data.js file
- [x] Remove extra console.log
- [x] Add a picture to gravitational force

### CODE REVIEW

**Comment by Amit366** [comment]
@laisfrigerio send a screenshot of the page

**Comment by laisfrigerio** [comment]
@Amit366  Screenshot:

screencapture-localhost-3000-classicalmechanics-calc-gravitation-Gravitational-Force-2021-10-01-07_53_31

**Comment by Amit366** [comment]
@laisfrigerio where is the calculator?? And also the design is not as similar to other calculators.

**Comment by laisfrigerio** [comment]
@Amit366 I correct the Error in loading the gravitational force page

 I didn't touch into css files. Is the same from main branch

**Comment by Amit366** [comment]
@laisfrigerio the css is common for everything. I think the css is not linked with the gravitational calculator part. Once check. If you are not getting it I will check it on Sunday.

**Comment by laisfrigerio** [comment]
@Amit366 A example page from Momentum localhost:

screencapture-localhost-3000-classicalmechanics-calc-Momentum-2021-10-01-08_18_05

I screenshot from product (Momentum)

screencapture-myfunwithphysics-web-app-classicalmechanics-calc-Momentum-2021-10-01-08_18_50

It's seems same css.

And this css is same from gravitational force

**Comment by Amit366** [comment]
@laisfrigerio where is the calculator in the gravitational part??

**Comment by laisfrigerio** [comment]
@Amit366 I dosen't call the calculator. I only fix error loading.

This is another issue to fix

**Comment by Amit366** [comment]
Screenshot (19)


This is the Css

**Comment by Amit366** [comment]
@laisfrigerio if u r facing any problem then I can help you tomorrow evening as now I am travelling now. So please keep ur doubts till tomorrow. I am sorry

**Comment by laisfrigerio** [comment]
@Amit366 I found and fix error to show gravitational force formula. See screenshot:

screencapture-localhost-3000-classicalmechanics-calc-gravitation-Gravitational-Force-2021-10-01-08_38_17

**Comment by Amit366** [comment]
@laisfrigerio that's good u fixed it but the font of formula is not same as the above image which I posted.

**Comment by Amit366** [comment]
@laisfrigerio see the formula is present in https://github.com/Amit366/FunwithPhysics/blob/main/funwithphysics/src/Components/Classical%20Mechanics/Topics/gravitation_Calculator.js. just check this folder.

**Comment by laisfrigerio** [comment]
@Amit366 formula seems correct to me.  The same content from screenshot and this file you share it.

**Comment by laisfrigerio** [comment]
@Amit366 the error is into formula content or css? I get lost here now

**Comment by Amit366** [comment]
@laisfrigerio maybe once check the css file and also the class names

**Comment by laisfrigerio** [comment]
> Screenshot (19)
> 
> This is the Css @laisfrigerio

In production it's not this font, look: https://myfunwithphysics.web.app/classicalmechanics/calc/Momentum

I think something break before my modifications

What's name of font?

**Comment by Amit366** [comment]
@laisfrigerio in localhost it's the same font as above.

**Comment by Amit366** [comment]
@laisfrigerio font family is cursive. Ok anyways I will look into the code base tomorrow.

**Comment by laisfrigerio** [comment]
@Amit366 I think you have somethimg in your localhost that must be pushed to main branch

**Comment by Amit366** [comment]
https://github.com/Amit366/FunwithPhysics/blob/main/funwithphysics/src/Components/Classical%20Mechanics/Topics/Calculator.css


Check this out @laisfrigerio

**Comment by laisfrigerio** [comment]
@Amit366  "cursive" font depends on each computer. Maybe I don't have this font installed in my computer, that's why my screenshot from localhost and in production mode to me is different

**Comment by Amit366** [comment]
@laisfrigerio not a problem. I will look into it.

**Pull request merged**
