### PR TITLE
Added Force Formula

### PR DESCRIPTION
**Pull request by Hiteshsukhwani29**
## Related Issue

- Info about Issue or bug

Fixes: #13 

#### Describe the changes you've made

Added the force section, added image, added the calculator function, added SI Units, added Dimensions

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | 
Screenshot 2021-08-04 171449
Screenshot 2021-08-05 001256
Screenshot 2021-08-04 171337
 |

### CODE REVIEW

**Comment by Amit366** [comment]
@Hiteshsukhwani29 just a small modification. Just make the heading force calculator align with the formula force=ma and also if possible give a border across the formula.

**Comment by Hiteshsukhwani29** [comment]
Okay

**Comment by Amit366** [comment]
@Hiteshsukhwani29 also I have asked to add a border on the formula??

**Comment by Amit366** [comment]
> @Hiteshsukhwani29 just a small modification. Just make the heading force calculator align with the formula force=ma and also if possible give a border across the formula.

**Comment by Hiteshsukhwani29** [comment]
it was not looking good

**Comment by Amit366** [comment]
A thin border will be nice @Hiteshsukhwani29

**Comment by Amit366** [comment]
It would give a text book feel

**Comment by Amit366** [comment]
@Hiteshsukhwani29 the image is giving the error. Have u added the image??

**Comment by Amit366** [comment]
@all-contributors please add @Hiteshsukhwani29  for code

**Pull request merged**
