### PR TITLE
Warning Fix: No duplicate props allowed #78

### PR DESCRIPTION
**Pull request by kunalkumar007**
Fixes: #78 
## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by Amit366** [comment]
@kunalkumar007 r u a participant of Hacktober fest?

**Comment by kunalkumar007** [comment]
@Amit366 Yes, I am looking forward to contributing to Hacktoberfest.😊

**Comment by Amit366** [comment]
@kunalkumar007 if you are contributing to Hacktober fest then I can accept it only after 1st october.

**Comment by kunalkumar007** [comment]
I will be happy about that but I was having a doubt that it will be selected as a Contribution to Hacktoberfest or not?

**Comment by kunalkumar007** [comment]
Hy @Amit366 , is this PR can be merged or there is some change you want to request?

**Comment by kunalkumar007** [comment]
Hy @Amit366, When accepted the PR must have the label hacktoberfest-accepted to count for the participants.

**Comment by Amit366** [comment]
@kumarishalini6 check if it is counted now.

**Comment by Amit366** [comment]
@all-contributors please add @kunalkumar007  for bug

**Pull request merged**
