### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by ashish-patwal**
## Related Issue

- Added gravitation section 

Fixes: #32

#### Describe the changes you've made

added the gravitation section , added the image , added the calculator function 

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>2021 08 03-22 19 36 screenshot
 </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@ashish-patwal send the ss

**Comment by Amit366** [comment]
@ashish-patwal Could u add all the formulas for gravitation one by one with different images

**Comment by ashish-patwal** [comment]
i did not get what you are trying to say ? Can you explain it ?

**Comment by Amit366** [comment]
Like there are many gravitation formulas , so could u add one after the other

**Comment by Amit366** [comment]
And also add  the reset button as done in other calculators.

**Comment by ashish-patwal** [comment]
> Like there are many gravitation formulas , so could u add one after the other

what other formulas are we talking about ?

**Comment by ashish-patwal** [comment]
There are a lot of other formulas related to Gravitation but i don't think we have a need to add all those here . Here i found a link of many different gravitation formulas . Have a look https://www.vedantu.com/formula/important-gravitation-formulas-for-jee

**Comment by Amit366** [comment]
@all-contributors please add @ashish-patwal  for code

**Pull request merged**
