### PR TITLE
custom scrollbar

### PR DESCRIPTION
**Pull request by kumarishalini6**
## Related Issue #42 

- Info about Issue or bug

Fixes: #42 

InkedFun With Physics - Personal - Microsoft​ Edge 7_17_2021 01_30_55 PM_LI

### CODE REVIEW

**Comment by kumarishalini6** [comment]
@Amit366  please have a look on this PR

**Comment by Amit366** [comment]
@kumarishalini6 can u reduce the width a little more? And also the color , I think u can make it a linear gradient but not white in between. The present one is good but it is getting hidden inside the background image.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 can u reduce the width a little more? And also the color , I think u can make it a linear gradient but not white in between. The present one is good but it is getting hidden inside the background image.

Ok

**Comment by kumarishalini6** [comment]
@Amit366 now check it, is it ok or not??

**Comment by Amit366** [comment]
@kumarishalini6 could u send the ss of the changes?

**Comment by kumarishalini6** [comment]
InkedFun With Physics - Personal - Microsoft​ Edge 7_17_2021 03_56_34 PM_LI

**Comment by Amit366** [comment]
@kumarishalini6 fill the form as soon as possible or else ur contribution will not be counted. Read the instructions in the slack.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 fill the form as soon as possible or else ur contribution will not be counted. Read the instructions in the slack.

Done

**Comment by Amit366** [comment]
You were just on time. If a little late then the leaderboard would have updated without ur contribution.

**Comment by kumarishalini6** [comment]
> You were just on time. If a little late then the leaderboard would have updated without ur contribution.

Can you please tell me where is leaderboard??

**Comment by Amit366** [comment]
They are still working on it. All the project admins have submitted the points of the participants. So as I was submitting u filled the form so u were on time.

**Comment by Amit366** [comment]
@all-contributors please add @kumarishalini6  for code

**Pull request merged**
