### PR TITLE
FAQs page

### PR DESCRIPTION
**Pull request by kumarishalini6**
## Related Issue

- Info about Issue or bug

Fixes: #43 

Fun With Physics - Personal - Microsoft​ Edge 7_20_2021 03_26_03 PM

### CODE REVIEW

**Comment by Amit366** [comment]
@kumarishalini6 do u want to work on calculators?

**Comment by kumarishalini6** [comment]
> @kumarishalini6 do u want to work on calculators?

I want but I know only simple calculator code

**Comment by Amit366** [comment]
@kumarishalini6 these are simple calculators only. If u want try out the force calculator. And if u want to work on it then dm me on slack for how to go about it.

**Comment by kumarishalini6** [comment]
> @kumarishalini6 these are simple calculators only. If u want try out the force calculator. And if u want to work on it then dm me on slack for how to go about it.

can i start after 2 days i have final sem exams

**Pull request merged**
