### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by aakankshabhende**
Closes : #21

### CODE REVIEW

**Comment by Amit366** [comment]
@aakankshabhende did the PR template appear while creating the PR??

**Comment by aakankshabhende** [comment]
No @Amit366 sir

**Comment by Amit366** [comment]
@aakankshabhende I request you to send the PR in the PR template format. As this PRs will again be reviewed by the organizers. That's why they asked us to ask the contributors to fill the forms.

**Comment by Amit366** [comment]
@aakankshabhende then u need to pull upstream into ur local system.

**Comment by Amit366** [comment]
If u don't know how to do or facing any difficulty u can dm me on slack

**Comment by aakankshabhende** [comment]
Okaay @Amit366 sir

**Comment by Amit366** [comment]
Send another PR with the PR template

**Pull request closed without merging**
