### PR TITLE
Sidenav added

### PR DESCRIPTION
**Pull request by aakankshabhende**
fixes: #7

### CODE REVIEW

**Comment by Amit366** [comment]
@aakankshabhende can u just add a pic?

**Comment by Amit366** [comment]
@aakankshabhende u have created separate links for each like electromagnetism, mechanics and all then why to create a separate drop down for Calculators. I was thinking since u have created them separately on the homepage so who ever wants to add calculator they can add it .

**Comment by aakankshabhende** [comment]
So should I remove the dropdown? @Amit366

**Comment by Amit366** [comment]
@aakankshabhende yes remove it. Just make the nav icons little bit bigger that's it.

**Comment by Amit366** [comment]
@aakankshabhende heyy u could have done the changes here itself. Why to create a new PR??

**Pull request merged**
