### PR TITLE
Moment of inertia added

### PR DESCRIPTION
**Pull request by akashsahu006**
## Related Issue

- Info about Issue or bug

Fixes: #[issue number that will be closed through this PR]
Issue number 97

#### Describe the changes you've made

I have added moment of inertia calculator for different bodies.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
|  Original
Screenshot (6)
 | <b>updated screenshot 1</b> |
Screenshot (3)
| <b>updated screenshot 2</b> |
Screenshot (4)
| <b>updated screenshot 3</b> |
Screenshot (5)

### CODE REVIEW

**Comment by Amit366** [comment]
@akashsahu006 why two PRs for same issue??

**Comment by akashsahu006** [comment]
I was having a hard time solving the merge conflict on the previous one. That's why I did that again after pulling.

**Comment by Amit366** [comment]
@akashsahu006 I asked u send the screen shot of the page

**Comment by akashsahu006** [comment]
I will do that right away

**Comment by akashsahu006** [comment]
i have added the images

**Comment by Amit366** [comment]
@all-contributors please add @aakankshabhende  for code

**Pull request merged**
