### PR TITLE
Added Gravitational Formulas

### PR DESCRIPTION
**Pull request by Hiteshsukhwani29**
Fixes: #32 
#### Describe the changes you've made

Added Below Formulas :
Gravitational_Force
Gravitational_Acceleration
Gravitational_Acceleration For Satellite
Orbital_Velocity
Escape_Velocity

### CODE REVIEW

**Comment by Amit366** [comment]
@Hiteshsukhwani29 may I know what exactly have u done??

**Comment by Hiteshsukhwani29** [comment]
> @Hiteshsukhwani29 may I know what exactly have u done??

As there was no component named classical mechanics. So i had created functions to calculate Gravitational Force, Acceleration, etc

**Comment by Amit366** [comment]
@Hiteshsukhwani29 what I wanted was ,on clicking classical mechanics it should open a contents page where there would be different topic names. Then on clicking the topic name a page should open where there is some content with images and then below it the calculator.

**Comment by Amit366** [comment]
If you had a doubt or if u were facing difficulty then u should have asked me. Because in ur PR there are just 4 formula.

**Comment by Hiteshsukhwani29** [comment]
> @Hiteshsukhwani29 what I wanted was ,on clicking classical mechanics it should open a contents page where there would be different topic names. Then on clicking the topic name a page should open where there is some content with images and then below it the calculator.

Sorry, I misunderstood the issue
I will work on it

**Comment by Amit366** [comment]
@Hiteshsukhwani29 ok any doubts ask me on slack.

**Pull request closed without merging**
