### PR TITLE
Added Images to Physics Content

### PR DESCRIPTION
**Pull request by Swastik1710**
## Related Issue
#12 

- Info about Issue or bug
There were no images present with the physics content

Fixes: #12 

#### Describe the changes you've made

Added the icon images to all the physics content

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: | 

**before**  <b>After
 </b>

### CODE REVIEW

**Comment by Swastik1710** [comment]
Hey @Amit366  please check this out and do let me know if any changes are required

**Comment by Amit366** [comment]
@Swastik1710 its nice but can u add any other image for thermodynamics. Its becoming similar to nuclear.

**Comment by Swastik1710** [comment]
Done!
Please have a look @Amit366

**Comment by Amit366** [comment]
@Swastik1710 send the pic.

**Comment by Swastik1710** [comment]
FireShot Capture 050 - Fun With Physics - localhost

Here it is.

**Comment by Amit366** [comment]
@Swastik1710 why did u change statistical mechanics?? And for thermodynamics instead of calculations can u place some image like heating of rod or kinetic theory of gas but don't place calculations.

**Comment by Swastik1710** [comment]
Ohh my bad.
I'll get back to you.

**Comment by Swastik1710** [comment]
FireShot Capture 050 - Fun With Physics - localhost

Is this one fine ?

**Comment by Amit366** [comment]
Nice!!

**Comment by Swastik1710** [comment]
I've pushed the code.
Please check it out .

**Comment by Amit366** [comment]
@Swastik1710 yes it will merged today itself.

**Comment by Swastik1710** [comment]
Hey @Amit366, I didn't get any google form link for this PR as I got for the PR #26.
Please have a look.

**Comment by Amit366** [comment]
@Swastik1710 u can fill that google form only. But send separately for both. Today only I automated it with GitHub.

**Comment by Amit366** [comment]
@all-contributors please add @Swastik1710  for contribution

**Comment by Amit366** [comment]
@all-contributors please add @Swastik1710  for code

**Pull request merged**
