### PR TITLE
Logo Added

### PR DESCRIPTION
**Pull request by techabhi08**
## Related Issue #2 

I have added a new logo.

Fixes: #2 

#### Describe the changes you've made

I have added a new folder named Logo which consists of an image1 that I have designed.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by Amit366** [comment]
@techabhi08 can u send ss of logo?

**Comment by techabhi08** [comment]
Screenshot (503)

**Comment by Amit366** [comment]
It's nice. Did u add it to the website??

**Comment by techabhi08** [comment]
No.

**Comment by techabhi08** [comment]
It would be better if you add it after merging. The problem being I am busy now-a-days in some project and would not be able to take out time. Sorry for inconvenience.

**Comment by Amit366** [comment]
Ok then. Not a problem.

**Comment by techabhi08** [comment]
Thank you sir for merging the PR. I hope to contribute more toward your projects in future

**Comment by Amit366** [comment]
@all-contributors please add @techabhi08  for design

**Pull request merged**
