### PR TITLE
Responsive Design

### PR DESCRIPTION
**Pull request by william-monroy**
## Related Issue

- Elements in the hero section and navbar was not responsive for mobile.

Fixes: #25

#### Describe the changes you've made

Add CSS files for each component and through media queries implement responsive design including horizontal orientation for mobile devices.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| original | updated |

### CODE REVIEW

**Comment by Amit366** [comment]
@william-monroy did u make it responsive for max-width 250px ??

**Comment by Amit366** [comment]
@william-monroy resolve the merge conflict

**Comment by william-monroy** [comment]
@Amit366 I fix responsive design for 250px devices. But I don't understand the problem to merge my commit.

**Comment by Amit366** [comment]
@william-monroy do one thing again pull the main repo. That will resolve the conflict

**Comment by william-monroy** [comment]
@Amit366 Could I send you another pull request in the correct way, please?

**Comment by william-monroy** [comment]
@Amit366 I resolved the conflicts with the new changes made to the page by the previous user.

**Comment by Amit366** [comment]
@william-monroy u could have just pulled the repo

**Comment by william-monroy** [comment]
@Amit366 That's what I did, and that's why with the new changes and conflict resolution my pull request is ready for review.

**Comment by Amit366** [comment]
@william-monroy Ok cool. It will be reviewed today itself.

**Comment by william-monroy** [comment]
Thanks, @Amit366

**Comment by Amit366** [comment]
@all-contributors please add @william-monroy for code

**Comment by Amit366** [comment]
@all-contributors please add @william-monroy for code

**Pull request merged**
